### ISSUE TITLE
server dies with error 500 when trying TUS upload with curl

### ISSUE THREAD

**Issue by individual-it** [owncloud/product#190]
noticed when tried to run the tests of https://github.com/tus/tus-js-client with ocis server
running this script makes ocis return ERROR 500 and showing an runtime error
```
#!/bin/bash

IFS=$'\r' #there is a CR (^M) at the end of the location URL, this helps to get rid of it
UUID=$(cat /proc/sys/kernel/random/uuid)
URL=https://localhost:9200/remote.php/dav/files/$UUID/
LOC=$(curl -k $URL -H 'Tus-Resumable: 1.0.0'  -H 'Upload-Length: 11' -H 'Upload-Metadata: filename ZmlsZS50eHQ=,filetype dGV4dC9wbGFpbg==,size MTE=,mtime MTU5ODU5MjQwMg==' --data-raw '' -v -ueinstein:relativity -s 2>&1 | grep Location: | cut -d" " -f3)

curl -k -XPATCH  -H 'Tus-Resumable: 1.0.0' -H 'Upload-Offset: 0' -H 'Content-Type: application/offset+octet-stream' --data-raw "hello world" -ueinstein:relativity -v ${LOC}
```

OCIS log:
```
key:"gid" value:<decoder:"plain" value:"30000" > > map:<key:"uid" value:<decoder:"plain" value:"20000" > > >  authenticated pkg=rgrpc service=reva traceid=fe5598dbb77bdf69642e7eb1988670fa
2020-08-28T11:45:57+05:45 INF unary code=OK end="28/Aug/2020:11:45:57 +0545" from=tcp://127.0.0.1:44984 pkg=rgrpc service=reva start="28/Aug/2020:11:45:57 +0545" time_ns=62918024 traceid=fe5598dbb77bdf69642e7eb1988670fa uri=/cs3.auth.provider.v1beta1.ProviderAPI/Authenticate user-agent=grpc-go/1.26.0
2020-08-28T11:45:57+05:45 INF unary code=OK end="28/Aug/2020:11:45:57 +0545" from=tcp://127.0.0.1:34404 pkg=rgrpc service=reva start="28/Aug/2020:11:45:57 +0545" time_ns=87568 traceid=fe5598dbb77bdf69642e7eb1988670fa uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.26.0
2020-08-28T11:45:57+05:45 INF unary code=OK end="28/Aug/2020:11:45:57 +0545" from=tcp://127.0.0.1:46878 pkg=rgrpc service=reva start="28/Aug/2020:11:45:57 +0545" time_ns=200509 traceid=fe5598dbb77bdf69642e7eb1988670fa uri=/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome user-agent=grpc-go/1.26.0
2020-08-28T11:45:57+05:45 INF unary code=OK end="28/Aug/2020:11:45:57 +0545" from=tcp://127.0.0.1:34422 pkg=rgrpc service=reva start="28/Aug/2020:11:45:57 +0545" time_ns=64423353 traceid=fe5598dbb77bdf69642e7eb1988670fa uri=/cs3.gateway.v1beta1.GatewayAPI/Authenticate user-agent=grpc-go/1.26.0
2020-08-28T11:45:57+05:45 INF core access token generated pkg=rhttp service=reva traceid=fe5598dbb77bdf69642e7eb1988670fa
[tusd] 2020/08/28 11:45:57 event="RequestIncoming" method="PATCH" path="/c6475cae-ee92-460f-8500-0a8d7f49e6cf" requestId="" 
2020-08-28T11:45:57+05:45 INF tusd routing: path=/c6475cae-ee92-460f-8500-0a8d7f49e6cf pkg=rhttp service=reva traceid=fe5598dbb77bdf69642e7eb1988670fa
[tusd] 2020/08/28 11:45:57 event="ChunkWriteStart" id="c6475cae-ee92-460f-8500-0a8d7f49e6cf" maxSize="11" offset="0" 
[tusd] 2020/08/28 11:45:57 event="ChunkWriteComplete" id="c6475cae-ee92-460f-8500-0a8d7f49e6cf" bytesWritten="11" 
2020-08-28 11:45:57.422222 I | http: panic serving 127.0.0.1:34884: runtime error: index out of range [1] with length 1
goroutine 115 [running]:
net/http.(*conn).serve.func1(0xc0000f2500)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x3066260, 0xc000055a20)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cs3org/reva/pkg/storage/fs/owncloud.(*ocfs).getVersionsPath(0xc000653d20, 0x3739c00, 0xc00065c000, 0xc000055740, 0x12, 0x0, 0x0)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/pkg/storage/fs/owncloud/owncloud.go:389 +0x427
github.com/cs3org/reva/pkg/storage/fs/owncloud.(*fileUpload).FinishUpload(0xc000fe43c0, 0x3739b80, 0xc0000d2010, 0x73, 0x0)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/pkg/storage/fs/owncloud/upload.go:344 +0x6e0
github.com/tus/tusd/pkg/handler.(*UnroutedHandler).finishUploadIfComplete(0xc00067c410, 0x3739b80, 0xc0000d2010, 0x373a640, 0xc000fe43c0, 0xc000917230, 0x24, 0xb, 0x0, 0xb, ...)
	/home/artur/go/pkg/mod/github.com/tus/tusd@v1.1.1-0.20200416115059-9deabf9d80c2/pkg/handler/unrouted_handler.go:681 +0x9d
github.com/tus/tusd/pkg/handler.(*UnroutedHandler).writeChunk(0xc00067c410, 0x3739b80, 0xc0000d2010, 0x373a640, 0xc000fe43c0, 0xc000917230, 0x24, 0xb, 0x0, 0xb, ...)
	/home/artur/go/pkg/mod/github.com/tus/tusd@v1.1.1-0.20200416115059-9deabf9d80c2/pkg/handler/unrouted_handler.go:671 +0x54b
github.com/tus/tusd/pkg/handler.(*UnroutedHandler).PatchFile(0xc00067c410, 0x7ff27c1fc128, 0xc000354d50, 0xc000544400)
	/home/artur/go/pkg/mod/github.com/tus/tusd@v1.1.1-0.20200416115059-9deabf9d80c2/pkg/handler/unrouted_handler.go:570 +0x638
github.com/cs3org/reva/internal/http/services/dataprovider.(*svc).setHandler.func1(0x7ff27c1fc128, 0xc000354d50, 0xc000544400)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/internal/http/services/dataprovider/dataprovider.go:173 +0x347
net/http.HandlerFunc.ServeHTTP(0xc000665320, 0x7ff27c1fc128, 0xc000354d50, 0xc000544400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/tus/tusd/pkg/handler.(*UnroutedHandler).Middleware.func1(0x7ff27c1fc128, 0xc000354d50, 0xc000544400)
	/home/artur/go/pkg/mod/github.com/tus/tusd@v1.1.1-0.20200416115059-9deabf9d80c2/pkg/handler/unrouted_handler.go:270 +0x8c5
net/http.HandlerFunc.ServeHTTP(0xc000665340, 0x7ff27c1fc128, 0xc000354d50, 0xc000544400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7ff27c1fc128, 0xc000354d50, 0xc000544200)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00065c870, 0x7ff27c1fc128, 0xc000354d50, 0xc000544200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.(*Server).getHandler.func1(0x7ff27c1fc128, 0xc000354d50, 0xc000544200)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/pkg/rhttp/rhttp.go:236 +0x287
net/http.HandlerFunc.ServeHTTP(0xc000653ee0, 0x7ff27c1fc128, 0xc000354d50, 0xc000544200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7ff27c1fc128, 0xc000354d50, 0xc000544000)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00065c900, 0x7ff27c1fc128, 0xc000354d50, 0xc000544000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/auth.New.func1.1(0x7ff27c1fc128, 0xc000354d50, 0xc000860400)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/internal/http/interceptors/auth/auth.go:246 +0xdaf
net/http.HandlerFunc.ServeHTTP(0xc00067a3f0, 0x7ff27c1fc128, 0xc000354d50, 0xc000860400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7ff27c1fc128, 0xc000354d50, 0xc000860300)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00065c930, 0x7ff27c1fc128, 0xc000354d50, 0xc000860300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/log.loggingHandler.ServeHTTP(0x36dd760, 0xc00065c930, 0x372ebc0, 0xc0000464b0, 0xc000860300)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/internal/http/interceptors/log/log.go:57 +0x297
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x372ebc0, 0xc0000464b0, 0xc000860200)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00065c960, 0x372ebc0, 0xc0000464b0, 0xc000860200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/appctx.handler.func1(0x372ebc0, 0xc0000464b0, 0xc000860100)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.2.1-0.20200826162318-c0f54e1f37ea/internal/http/interceptors/appctx/appctx.go:52 +0x5e9
net/http.HandlerFunc.ServeHTTP(0xc00013a150, 0x372ebc0, 0xc0000464b0, 0xc000860100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc000668690, 0x372ebc0, 0xc0000464b0, 0xc00011ee00)
	/home/artur/go/pkg/mod/go.opencensus.io@v0.22.4/plugin/ochttp/server.go:92 +0x2b9
net/http.serverHandler.ServeHTTP(0xc000686000, 0x372c7c0, 0xc00091c2a0, 0xc00011ee00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000f2500, 0x3739b40, 0xc00082ee40)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
2020-08-28T11:45:57+05:45 ERR error doing PATCH request to data service error="Patch http://localhost:9164/data/c6475cae-ee92-460f-8500-0a8d7f49e6cf: EOF" pkg=rhttp service=reva traceid=fe5598dbb77bdf69642e7eb1988670fa
2020-08-28T11:45:57+05:45 ERR http end="28/Aug/2020:11:45:57 +0545" host=127.0.0.1 method=PATCH pkg=rhttp proto=HTTP/1.1 service=reva size=0 start="28/Aug/2020:11:45:57 +0545" status=500 time_ns=128465592 traceid=fe5598dbb77bdf69642e7eb1988670fa uri=/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTk4NjgwODU3LCJpYXQiOjE1OTg1OTQ0NTcsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE2NC9kYXRhL2M2NDc1Y2FlLWVlOTItNDYwZi04NTAwLTBhOGQ3ZjQ5ZTZjZiJ9.GmTg5b_nJTF8le8qlIGKDy0E5eoNNvZheE9OTibcM2w url=/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTk4NjgwODU3LCJpYXQiOjE1OTg1OTQ0NTcsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE2NC9kYXRhL2M2NDc1Y2FlLWVlOTItNDYwZi04NTAwLTBhOGQ3ZjQ5ZTZjZiJ9.GmTg5b_nJTF8le8qlIGKDy0E5eoNNvZheE9OTibcM2w
```

**Comment by individual-it** [comment]
this seems not to happen anymore on the current ocis master. TUS upload works when using `einstein` instead of a random uuid in the URL and a 404 Error is returned when using an random UUID, what also looks correct
