### ISSUE TITLE
logout sometimes does not work

### ISSUE THREAD

**Issue by individual-it** [owncloud/product#266]
phoenix tests with ocis sometimes fail in the logout.

## How to reproduce:

keep on running tests/acceptance/features/webUILogin/login.feature:20 as explained in https://owncloud.github.io/clients/web/testing/#with-ocis-backend till it fails
![logout](https://user-images.githubusercontent.com/2425577/95738333-c7bca480-0ca8-11eb-8782-e221717f4fc3.gif)

## observations:
The logout button is clicked, the browser redirected but ends up again on the files-page.
Sequence of screenshots:
![image](https://user-images.githubusercontent.com/2425577/95738547-2550f100-0ca9-11eb-9cb0-bb215dd9fe51.png)

![image](https://user-images.githubusercontent.com/2425577/95738661-4a456400-0ca9-11eb-993e-2ca144880a5f.png)
![image](https://user-images.githubusercontent.com/2425577/95738682-54676280-0ca9-11eb-81d8-d27c205fc9ec.png)
![image](https://user-images.githubusercontent.com/2425577/95738706-621ce800-0ca9-11eb-9139-d6afad77ee52.png)
![image](https://user-images.githubusercontent.com/2425577/95738735-6c3ee680-0ca9-11eb-99ee-a3411ae1a095.png)
![image](https://user-images.githubusercontent.com/2425577/95738759-752fb800-0ca9-11eb-974d-04da1a2ee8ab.png)

## console log
```
4:27:01 PM - SEVERE - https://localhost:9200/img/app.png - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:01 PM - SEVERE - https://localhost:9200/#/login - Error while trying to use the following icon from the Manifest: https://localhost:9200/img/app.png (Download error or resource isn't a valid image)
4:27:03 PM - SEVERE - https://localhost:9200/img/app.png - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:03 PM - SEVERE - https://localhost:9200/#/oidc-callback?code=ublDAawKEGpQ58GPdASvd6YAuOjpw5eO&scope=openid%20profile%20email&session_state=84c5dfa95614b9548ea37d565e920bf314ba565999f38d0149b8d1776c261097.Gbj2l7c0E9_RKvxQNYa8clUwSa5KdBnAHYaIwt8KzJs%3D&state=1e08528ab10243fd82b7dc84bdb9c428 - Error while trying to use the following icon from the Manifest: https://localhost:9200/img/app.png (Download error or resource isn't a valid image)
4:27:04 PM - SEVERE - https://localhost:9200/core/core.bundle.js 359:123160 Uncaught SyntaxError: Unexpected end of JSON input
4:27:04 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/data.tar.gz?a=1&c=9e6936ec73ce5df6bd55f3b609b4f648&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:04 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/block-aligned-plus-one.txt?a=1&c=a943a308204fe2bfa84413c27b460cb0&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:04 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/block-aligned.txt?a=1&c=567bf293f2dc39d38bace879af4c9851&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:04 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/data.zip?a=1&c=481dcbc6d26d58df87fb19e33a1c84d7&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:04 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/'single'quotes.txt?a=1&c=75da644b4b8913fc8ec6cab59a470fdc&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:04 PM - SEVERE - https://localhost:9200/img/app.png - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:04 PM - SEVERE - https://localhost:9200/#/files/list - Error while trying to use the following icon from the Manifest: https://localhost:9200/img/app.png (Download error or resource isn't a valid image)
4:27:05 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/block-aligned.txt?a=1&c=567bf293f2dc39d38bace879af4c9851&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:05 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/data.tar.gz?a=1&c=9e6936ec73ce5df6bd55f3b609b4f648&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:05 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/block-aligned-plus-one.txt?a=1&c=a943a308204fe2bfa84413c27b460cb0&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:05 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/'single'quotes.txt?a=1&c=75da644b4b8913fc8ec6cab59a470fdc&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:05 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/data.zip?a=1&c=481dcbc6d26d58df87fb19e33a1c84d7&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:05 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/desktopapp.svg?a=1&c=59f665f4cdce03eda601be9fbcf139e3&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:05 PM - SEVERE - https://localhost:9200/core/core.bundle.js 359:123160 Uncaught SyntaxError: Unexpected end of JSON input
4:27:06 PM - SEVERE - https://localhost:9200/core/core.bundle.js 16:11545 TypeError: Cannot read property 'hide' of undefined
    at s.$_ocDrop_close (https://localhost:9200/core/core.bundle.js:345:139937)
    at Bt (https://localhost:9200/core/core.bundle.js:17:11207)
    at HTMLDivElement.n (https://localhost:9200/core/core.bundle.js:17:12918)
    at HTMLDivElement.Wr.o._wrapper (https://localhost:9200/core/core.bundle.js:17:48113)
4:27:06 PM - SEVERE - https://localhost:9200/core/core.bundle.js 364:15928 
4:27:06 PM - SEVERE - https://localhost:9200/core/core.bundle.js 364:15928 
4:27:06 PM - SEVERE - https://localhost:9200/img/app.png - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:06 PM - SEVERE - https://localhost:9200/#/oidc-callback?code=eV5-W7Z_uSdbx6H3lyBBjSOJ5D-5Ft6v&scope=openid%20profile%20email&session_state=822352e9f465359a81142f3d0dae4fc545378786123c6a68cc32f2832bc5a9f8.N6EUYAK35dmBycVik7-2OWhUo_egZbICpcl4fR_-v44%3D&state=60352d893f304fb8b619702a2d9bd9d6 - Error while trying to use the following icon from the Manifest: https://localhost:9200/img/app.png (Download error or resource isn't a valid image)
4:27:07 PM - SEVERE - https://localhost:9200/core/core.bundle.js 359:123160 Uncaught SyntaxError: Unexpected end of JSON input
4:27:07 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/'single'quotes.txt?a=1&c=75da644b4b8913fc8ec6cab59a470fdc&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:07 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/block-aligned-plus-one.txt?a=1&c=a943a308204fe2bfa84413c27b460cb0&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:07 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/data.zip?a=1&c=481dcbc6d26d58df87fb19e33a1c84d7&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:07 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/block-aligned.txt?a=1&c=567bf293f2dc39d38bace879af4c9851&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
4:27:07 PM - SEVERE - https://localhost:9200/remote.php/dav/files/user1/data.tar.gz?a=1&c=9e6936ec73ce5df6bd55f3b609b4f648&preview=1&scalingup=0 - Failed to load resource: the server responded with a status of 404 (Not Found)
```

## OCIS log
```
2020-10-12T16:40:38+05:45 INF access token is already provided pkg=rhttp service=storage traceid=09b973acc3880419061acfca601237fd
2020-10-12T16:40:38+05:45 INF http end="12/Oct/2020:16:40:38 +0545" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=262 start="12/Oct/2020:16:40:38 +0545" status=200 time_ns=73405 traceid=09b973acc3880419061acfca601237fd uri=/data/accounts/user1 url=/data/accounts/user1
2020-10-12T16:40:38+05:45 INF access token is already provided pkg=rhttp service=storage traceid=6cddb18a09518372778df017f5112df0
2020-10-12T16:40:38+05:45 INF http end="12/Oct/2020:16:40:38 +0545" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=262 start="12/Oct/2020:16:40:38 +0545" status=200 time_ns=81673 traceid=6cddb18a09518372778df017f5112df0 uri=/data/accounts/user1 url=/data/accounts/user1
2020-10-12T16:40:38+05:45 INF access token is already provided pkg=rhttp service=storage traceid=dde898e75f1f11e68b3ce8c785600b88
2020-10-12T16:40:38+05:45 INF http end="12/Oct/2020:16:40:38 +0545" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=262 start="12/Oct/2020:16:40:38 +0545" status=200 time_ns=67959 traceid=dde898e75f1f11e68b3ce8c785600b88 uri=/data/accounts/user1 url=/data/accounts/user1
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:49172 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=80923 traceid=b9d1d484f60d0bcc7f303d40cf0c00a4 uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:49172 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=77407 traceid=90a87e2ad59d2094a92826faf806d248 uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:34352 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=574417 traceid=b9d1d484f60d0bcc7f303d40cf0c00a4 uri=/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:48932 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=2033602 traceid=b9d1d484f60d0bcc7f303d40cf0c00a4 uri=/cs3.gateway.v1beta1.GatewayAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:34352 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=194041 traceid=90a87e2ad59d2094a92826faf806d248 uri=/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:48932 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=2889628 traceid=90a87e2ad59d2094a92826faf806d248 uri=/cs3.gateway.v1beta1.GatewayAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF access token is already provided pkg=rhttp service=storage traceid=d9e53ba581d83066986f97bb63a5f9ac
2020-10-12T16:40:38+05:45 INF http end="12/Oct/2020:16:40:38 +0545" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=262 start="12/Oct/2020:16:40:38 +0545" status=200 time_ns=117220 traceid=d9e53ba581d83066986f97bb63a5f9ac uri=/data/accounts/user1 url=/data/accounts/user1
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:49172 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=89292 traceid=c7fc862998b7406a3bd9452fbb78a5eb uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:34352 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=237785 traceid=c7fc862998b7406a3bd9452fbb78a5eb uri=/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:48932 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=2012693 traceid=c7fc862998b7406a3bd9452fbb78a5eb uri=/cs3.gateway.v1beta1.GatewayAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:49172 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=106445 traceid=e09bd34a4758791e6e535b4fbb89fe9c uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:34352 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=251100 traceid=e09bd34a4758791e6e535b4fbb89fe9c uri=/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:48932 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=1223051 traceid=e09bd34a4758791e6e535b4fbb89fe9c uri=/cs3.gateway.v1beta1.GatewayAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF access token is already provided pkg=rhttp service=storage traceid=e27c5de936db8e98ab88f11a411337f6
2020-10-12T16:40:38+05:45 INF http end="12/Oct/2020:16:40:38 +0545" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=262 start="12/Oct/2020:16:40:38 +0545" status=200 time_ns=159024 traceid=e27c5de936db8e98ab88f11a411337f6 uri=/data/accounts/user1 url=/data/accounts/user1
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:49172 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=88180 traceid=2478bbd35edfaad4c4a80102e3df542e uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:34352 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=298773 traceid=2478bbd35edfaad4c4a80102e3df542e uri=/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:38+05:45 INF unary code=OK end="12/Oct/2020:16:40:38 +0545" from=tcp://127.0.0.1:48932 pkg=rgrpc service=storage start="12/Oct/2020:16:40:38 +0545" time_ns=6948724 traceid=2478bbd35edfaad4c4a80102e3df542e uri=/cs3.gateway.v1beta1.GatewayAPI/CreateHome user-agent=grpc-go/1.26.0
2020-10-12T16:40:47+05:45 INF access token is already provided pkg=rhttp service=storage traceid=adda276d1e62b0cdd0fdef7a2ae6ca16
2020-10-12T16:40:47+05:45 INF http end="12/Oct/2020:16:40:47 +0545" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=262 start="12/Oct/2020:16:40:47 +0545" status=200 time_ns=272498 traceid=adda276d1e62b0cdd0fdef7a2ae6ca16 uri=/data/accounts/user1 url=/data/accounts/user1
2020-10-12T16:40:47+05:45 INF unary code=OK end="12/Oct/2020:16:40:47 +0545" from=tcp://127.0.0.1:56076 pkg=rgrpc service=storage start="12/Oct/2020:16:40:47 +0545" time_ns=4259961 traceid=e260546a48610911a3ffbb175175b6df uri=/cs3.storage.provider.v1beta1.ProviderAPI/Delete user-agent=grpc-go/1.26.0
2020-10-12T16:40:47+05:45 INF deleted account id=user1 service=accounts

**Comment by individual-it** [comment]
JIRA issue https://jira.owncloud.com/browse/OCIS-699

**Comment by DeepDiver1975** [comment]
> 4:27:06 PM - SEVERE - https://localhost:9200/core/core.bundle.js 16:11545 TypeError: Cannot read property 'hide' of undefined
>     at s.$_ocDrop_close (https://localhost:9200/core/core.bundle.js:345:139937)
>     at Bt (https://localhost:9200/core/core.bundle.js:17:11207)
>     at HTMLDivElement.n (https://localhost:9200/core/core.bundle.js:17:12918)
>     at HTMLDivElement.Wr.o._wrapper (https://localhost:9200/core/core.bundle.js:17:48113)

this error in phoenix potentially breaks the flow ....

**Comment by micbar** [comment]
@LukasHirt Does that help?

**Comment by LukasHirt** [comment]
I'll see if that will fix it. Thanks for the pointer!

**Comment by LukasHirt** [comment]
Nope, getting rid of the error doesn't change a thing.

**Comment by DeepDiver1975** [comment]
> 4:27:05 PM - SEVERE - https://localhost:9200/core/core.bundle.js 359:123160 Uncaught SyntaxError: Unexpected end of JSON input

this then? no idea where this is coming from ....
